language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

before_script:
  - ./build.sh

script:
  - vendor/bin/phpunit --debug --stop-on-error --stop-on-failure
